
export const villas = [
  {
    id: 1,
    name: "Jaycee Silent Diesel Generators",
    specification: "Silent Generators",
    category: "5 KVA- 45KVA",
    guests: "Eicher Engine(198ES)",
    bedrooms: "Diesel ",
    bathrooms: "<75DBA",
    squareMeter: "50 L",
    rating: 4.7,
    image: "/product_03.jpg",
    dailyRent: "1500000",
  },
  {
    id: 2,
    name: "Jaycee Super Silent Generators ",
    /*location: "Italy",*/
    category: "10 KVA",
    guests: "Eicher Engine(222ES)",
    bedrooms: "Diesel",
    bathrooms: "58DBA",
    squareMeter: "55L",
    rating: 4.4,
    image: "/supersilent.jpg",
    dailyRent: "400000",
  },
  {
    id: 3,
    name: "Jaycee Diesel Generators",
    /*location: "Greece",*/
    category: "40-45KVA",
    guests: "Eicher Engine(422TCI)",
    bedrooms: "Diesel",
    bathrooms: "85DBA",
    squareMeter: "100L",
    rating: 4.9,
    image: "/BIGD.webp",
    dailyRent: "320000",
  },
  {
    id: 4,
    name: "Jaycee Ultra Silent Generators",
    /*location: "Italy",*/
    category: "20KVA",
    guests: "Eicher Engine(248ESI)",
    bedrooms: "Diesel",
    bathrooms: "60DBA",
    squareMeter: "270L",
    rating: 5.0,
    image: "/ultra1.jpg",
    dailyRent: "20000",
  },
  {
    id: 5,
    name: "Jaycee DSilent Generators",
    /*location: "Greece",*/
    category: "100KVA",
    guests: "TMTL Engine(1401ES)",
    bedrooms: "Diesel",
    bathrooms: "110DB",
    squareMeter: "300L",
    rating: 4.0,
    image: "/100KVADG.jpg",
    dailyRent: "2000000",
  },
  {
    id: 6,
    name: "Jaycee Silent Pro Generators",
    /*location: "Greece",*/
    category: "70KVA",
    guests: "Eicher Engine(250ES)",
    bedrooms: "Diesel",
    bathrooms: 6,
    squareMeter: "60DBA",
    rating: 4.9,
    image: "/Pro.jpg",
    dailyRent: "320000",
  },
  /*
  {
    id: 7,
    name: "Villa Sunset",
    location: "Italy",
    category: "Mountains",
    guests: "hjk",
    bedrooms: 8,
    bathrooms: 10,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "280",
  },
  {
    id: 8,
    name: "White Lady",
    location: "Italy",
    category: "Seaside",
    guests: "fgh",
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "400",
  },
  {
    id: 9,
    name: "Thebes",
    location: "Greece",
    category: "Seaside",
    guests: "upo",
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "180",
  },*/
];

